In [2]:
import numpy as np

In [3]:
# 1st way to create a numpy array
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
# 2nd way
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [5]:
# 2-D array
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
# Shape of array
m.shape

(2, 3)

In [7]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n.shape

(15,)

In [9]:
n.reshape(3, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [11]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
a = np.array([1, 2, 3])
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
p = np.ones((2, 3), int)
q = 2*p
np.vstack([p, q])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
np.hstack((p, q))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [17]:
r = np.arange(36)
r.resize((6, 6))
r[2, 2]
r[3, 3:]
r[0:2, :-1]
r[-1::2]
r[np.where((r>=5) & (r<=10))]

array([ 5,  6,  7,  8,  9, 10])

In [18]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [20]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
r3 = r.copy()
r3

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
r3[:] = 5
r3

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [24]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [25]:
old = np.array([[1, 1, 1],[1, 1, 1]])

In [26]:
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [27]:
for count, row in enumerate(r, 1):
    print("{0}th row is: {1}".format(count, row))

1th row is: [0 0 0 3 4 5]
2th row is: [ 0  0  0  9 10 11]
3th row is: [ 0  0  0 15 16 17]
4th row is: [18 19 20 21 22 23]
5th row is: [24 25 26 27 28 29]
6th row is: [30 31 32 33 34 35]


In [28]:
# Resize
test = np.arange(1, 10)
test
test.resize(3, 3)
test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# Reshape
test2 = np.arange(1, 10).reshape(3, 3)
test2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
for i, j in zip(test2, test2**2):
    print("{i} + {j} = {k}".format(i=i, j=j, k=i+j))

[1 2 3] + [1 4 9] = [ 2  6 12]
[4 5 6] + [16 25 36] = [20 30 42]
[7 8 9] + [49 64 81] = [56 72 90]


In [31]:
quiz = np.arange(36).reshape(6, 6)
quiz

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
quiz[0:6, ::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [33]:
quiz[2:4, 2:4]

array([[14, 15],
       [20, 21]])